#!/usr/bin/env bash
# PROTOTYPE launcher for #6 (walking skeleton). Throwaway — the real thing is Go.
# One repo, one profile. No profile switching, no port publishing, no clipboard.
set -euo pipefail

IMAGE="${KOMORA_IMAGE:-localhost/komora-skeleton:latest}"
AGENT_UID=1000
AGENT_GID=1000

cmd="${1:-run}"; shift || true
repo="$(cd "${1:-$PWD}" && pwd)"; shift || true
name="komora-$(basename "$repo")"
vol_home="${name}-home"

# --- Credentials (#12): a per-profile 0700 dir holding nothing but that
# profile's credential. The host's live file is respected via CLAUDE_CONFIG_DIR
# rather than assuming ~/.claude, and it is *copied* rather than mounted: the
# chamber must be able to write (rotation would wedge on a read-only mount),
# but it must not be able to write back to the host's live credential.
profile="${KOMORA_PROFILE:-default}"
host_cfg="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
profile_dir="$HOME/.local/share/komora/profiles/$profile"
cred_src="$profile_dir/.credentials.json"

stage_credentials() {
  mkdir -p "$profile_dir"; chmod 700 "$profile_dir"
  if [[ -f "$host_cfg/.credentials.json" ]]; then
    cp "$host_cfg/.credentials.json" "$cred_src"
    chmod 600 "$cred_src"
  else
    echo "komora: no credential found at $host_cfg/.credentials.json" >&2
    exit 1
  fi
}

# --- ADR-0002: every uid-naming operation runs inside the chamber's own userns.
KEEPID=(--userns="keep-id:uid=${AGENT_UID},gid=${AGENT_GID}")

# Repair is idempotent and ~0.24s, so it runs unconditionally on volume
# creation rather than trying to detect the bad case (ADR-0002 §2).
ensure_volume() {
  podman volume exists "$vol_home" 2>/dev/null || podman volume create "$vol_home" >/dev/null
  podman run --rm "${KEEPID[@]}" --user 0:0 -v "$vol_home:/home/agent" "$IMAGE" \
    chown -R "${AGENT_UID}:${AGENT_GID}" /home/agent
}

# --- ADR-0003: pull named values, never mount a config file.
# Resolution order: komora's own config -> host global -> repo local -> none.
resolve_git() {
  local key="$1"
  git config --file "$HOME/.config/komora/gitconfig" "$key" 2>/dev/null && return 0
  git config --global "$key" 2>/dev/null && return 0
  git -C "$repo" config --local "$key" 2>/dev/null && return 0
  return 1
}

# Derived config: rewritten on every start, so the chamber holds a copy and
# never the truth (ADR-0003 §2).
write_gitconfig() {
  local name email
  name="$(resolve_git user.name || true)"
  email="$(resolve_git user.email || true)"

  if [[ -z "$name" || -z "$email" ]]; then
    echo "komora: no git identity found." >&2
    echo "  checked: komora config (~/.config/komora/gitconfig)," >&2
    echo "           host global (git config --global)," >&2
    echo "           repo local ($repo/.git/config)" >&2
    echo "  fix with: komora git config user.name '<name>'" >&2
    if [[ "${KOMORA_ASSUME_YES:-}" != "1" ]]; then
      read -r -p "Start without git identity? [y/N] " reply
      [[ "$reply" == [yY]* ]] || { echo "komora: aborted." >&2; exit 1; }
    fi
  fi

  local tmp; tmp="$(mktemp)"
  {
    echo "# Generated by komora on every chamber start. Edits are discarded."
    [[ -n "$name" ]]  && printf '[user]\n\tname = %s\n' "$name"
    [[ -n "$email" ]] && printf '\temail = %s\n' "$email"
    printf '[init]\n\tdefaultBranch = %s\n' "$(resolve_git init.defaultBranch || echo main)"
  } > "$tmp"

  podman run --rm "${KEEPID[@]}" -v "$vol_home:/home/agent" \
    -v "$tmp:/tmp/gitconfig:ro" "$IMAGE" \
    cp /tmp/gitconfig /home/agent/.gitconfig
  rm -f "$tmp"
}

run_chamber() {
  ensure_volume
  stage_credentials
  write_gitconfig
  podman run --rm -it "${KEEPID[@]}" \
    --name "$name" \
    --hostname "$(basename "$repo")" \
    -v "$repo:/work:z" \
    -v "$vol_home:/home/agent" \
    -v "$cred_src:/home/agent/.claude/.credentials.json" \
    -w /work \
    -e TERM="$TERM" -e COLORTERM="${COLORTERM:-}" \
    "$IMAGE" "$@"
}

case "$cmd" in
  run)     if [[ $# -gt 0 ]]; then run_chamber "$@"; else run_chamber /bin/zsh -l; fi ;;
  shell)   run_chamber /bin/zsh -l ;;
  destroy) podman rm -f "$name" 2>/dev/null || true
           podman volume rm -f "$vol_home" 2>/dev/null || true
           echo "destroyed: $name" ;;
  *)       echo "usage: chamber.sh {run|shell|destroy} [repo]" >&2; exit 2 ;;
esac
